### ISSUE TITLE
ssl.SSLError when waiting for snapshots to complete

### ISSUE THREAD

**Issue by gcallaghan** [brkt/brkt-cli#30]
```shell
Traceback (most recent call last):
  File "/usr/local/bin/brkt", line 9, in <module>
    load_entry_point('brkt-cli==0.9a1', 'console_scripts', 'brkt')()
  File "/usr/local/lib/python2.7/dist-packages/brkt_cli/__init__.py", line 918, in main
    encrypted_ami_name=values.encrypted_ami_name
  File "/usr/local/lib/python2.7/dist-packages/brkt_cli/__init__.py", line 603, in run
    aws_svc, snap_guest.id, snap_bsd.id, snap_grub.id, snap_log.id)
  File "/usr/local/lib/python2.7/dist-packages/brkt_cli/__init__.py", line 326, in _wait_for_snapshots
    snapshots = svc.get_snapshots(*snapshot_ids)
  File "/usr/local/lib/python2.7/dist-packages/brkt_cli/service.py", line 152, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/brkt_cli/service.py", line 255, in get_snapshots
    return self.conn.get_all_snapshots(snapshot_ids)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2460, in get_all_snapshots
    [('item', Snapshot)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1171, in get_list
    body = response.read()
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 585, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out
```

**Comment by Kuzmin** [comment]
Couldn't we close this by now?

**Comment by bburtin** [comment]
Closing this issue.  We're tracking it in JIRA.
